### PR TITLE
Add functionality

### PR DESCRIPTION
**Pull request by HookyQR**
This PR:
* add zone colours to the HR graph
* allow black background
* improve memory use (you may be able to use your fonts after this)
* add semiround watcface implementation (effectively pull Emma's Run back in to here)

There is still much redundant code between the semiround and round implementations. There is little need to DRY this unless/until bugs are identified.

### CODE REVIEW

**Comment by myneur** [comment]
Thank you @HookyQR for the contribution. I like that you added hr zone into the chart and supported more devices and saved some memory. In order to merge it there are some gaps to be fixed:

**The heart rate trend is better to show in a fixed scale** 
The purpose of the chart is to show how much the hr differs in time. When scaling the chart, you actually don't have a clue if the difference is 10 beats or 100 beats. If we just set a fixed scale to 1/2 that works the best for most of the cases. The graph can span 100 beats and you see just by looking into the chart how much actually your heart rate varies: if these are just a small changes or big differences (like on intervals). 
Such fixed-scale approach is not achievable for the pace chart, because that can vary much more, but for works perfectly for the heart rate. 
In order to make the fixed-scale work it needs to deal with the fact that the chart can run out of the height. In the former implementation, that was solved by showing the chart at the bottom and drawing the chart outside of boundaries by the lightest gray. Cutting that off could work as well, but dimming it to gray and show it outside of the boundaries looked pretty cool and it does not happen often. 

**Small tweaks that will be easy to fix**
- I like how you fixed a problem with variable fonts and bad font-height in older watches, but 240px screen is not a good predictor to decide which font is shown. Fenix 5s has the same height of 218px as Fenix 3, but the new font. 
- it is good to keep the threshold not to show a pace-diff when the lap pace differs just a little from the current pace, because Garmin devices' current pace is fluctuating a lot because of a poor precision, so it jumps up and down constantly, which is more confusing than helping. For that reason there was a threshold not to shaw small differences in the paceDiff indicator. Now on the fenix 5 and 5x the lap pace label is too high, while on 5s it is OK. 

If you are able to iterate on that, that would be great and I'll be happy to merge it. 
If not, I might find some time to iterate on it by myself in the future. 
One way or the other, I believe we'll finally merge it. 
Thanks again for your time and the contribution.

**Comment by HookyQR** [comment]
I disagree with your point about the heart rate trend. As it now shows the zone colour, it provides a better reference to the scale of the chart - currently, even though it's fixed, there's no scale reference. The only time the chart will show a single colour is when the users HR has been in the same zone for the entire chart span, when that is the case the expanded (scaled) view helps anyway. I don't like the idea of drawing outside of the chart space, but it's your app, so it's your call, let me know.

I'm not sure which of the text elements you're referring to about the Fenix 3 vs Fenix 5s. They both look fine to me on the simulator. The distance units sits a little high on the Fenix 3, but I don't think it detracts from the display. Please provide a little more direction (specific issue) on this one.

As for the threshold, it's unnecessary in my code because the `diff` is an integer, so it won't be drawn unless there's at least a 15 sec difference. You're version would draw one from a `(3,15]` sec difference, two for `(15,30]` and three for `30+`. My version draws one for `[15,30)`, two for `[30,45)` and three for `45+`, which is more like what I thought you were after anyway.

**Comment by myneur** [comment]
Hi, I mean the [alignment of the lap pace label](https://drive.google.com/file/d/0B98rO91GOxZrNHp6LThHS1BDRjQ/view?usp=sharing). 

Speaking on the scale: the zone colors are a great improvement but when running, there is no time to analyze the chart and checking where are the boundaries of the colors to understand the scale. Recovery runs have quite stable heart rate trend. Like here: 
https://drive.google.com/file/d/0B98rO91GOxZrbE15bnVsZUFUWmM/view?usp=sharing
What's the story told by this chart? Actually the hr fluctuated just couple of the beats, but the zoomed-in charts make a false impression there is a big variation. (these charts are not exactly the same, these were just similar simulations run in sequence, just to illustrate the point that when the scale is fixed, you are sure what the chart actually mean and it is the same on every run). 
Colors in the chart helps, but only when you cross at least 3 zones and you must be thinking about it. I don't think there is a value to zoom-in a very precise chart of how the heart rate varies plus minus two three beats. Having a 100 beats height on the chart worked for me well on all runs I did. 


To the pace diff: good, I didn't get it from the code. The 15s is just too much. That would make a huge difference without indicating you are slowing down or speeding up and the pace does not fluctuate that much. I learned that threshold works well by testing it on runs. But this will be an easy fix.

**Comment by myneur** [comment]
Actually testing your slightly modified code on couple of runs: let's do it next way:
- initially (most detailed) scale will be 1px per beat
- let's only scale it down when max-min of the visible part would not fit into the chart, but do not zoom-in
That way there always will be at last 3 zones in the chart and the initial scale will be understandable. 
That seems to me working good as well.

**Comment by myneur** [comment]
FYI @HookyQR I fixed that for round watch so far. I'll update it after a test run.

**Comment by myneur** [comment]
@HookyQR after some testing runs I found one more thing to be fixed: the updated charts don't work when HR signal drops or runner stopped for a lap. An an easy fix will be to make charts skip null values (that do not count into min/max). 

A question to your code: is it actually possible to compile one version for a round and semi-round watch or there must be two apps in the store? I didn't find a way how to compile it together.

**Comment by HookyQR** [comment]
You can compile it once for both. The compiler (prior to 2.4.0beta at least) uses the correct parts for the particular device.

**Comment by myneur** [comment]
So for such version it will work just to omit -d <device> option? Or how to specify which devices to compile it for? Because for the older compiler it does not work. It will create just one version. 
Better option might be to compile just one version, but conditionally set a method to draw values by SCREEN_SHAPE_SEMI_ROUND constant. That will reuse the code instead of having 2 separate versions.

**Comment by HookyQR** [comment]
When you compile for a .prg you just get one version. When you package (-e) it will compile for all devices. Leave out the -d (I think it gets ignored anyway)

**Comment by HookyQR** [comment]
Remember to compile for release (-r) or the executable will be bigger, and in some cases may exceed the limit.

**Comment by myneur** [comment]
I finally found the time to incorporate it into the watch. It took a looog looong time, but thank for your update, I took the necessity to update for F6 an opportunity to update it. I gave you the credits both in the code and the web. Thank you for the contribution.

**Pull request merged**
